import axios, { Axios } from 'axios'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { useRouter } from 'next/router'
import { useContext, useState } from 'react'
import AuthenticationContext from '../context/AuthenticationContext'
import styles from '../styles/Home.module.css'

export default function Home(props) {
  const {user, logout} = useContext(AuthenticationContext)
  const router = useRouter()
  const[title, setTitle] = useState('')
  const[snippet, setSnippet] = useState('')
  const[description, setDescription] = useState('')
  const[image, setImage] = useState(null)



  const blogs = props.data

  const submitHandler = async (e) =>{
    e.preventDefault();
    console.log(user)
    // console.log(blog)
    // console.log(text)


  //   console.log(email)

    const options = {
        method: "POST",
        body:JSON.stringify({
          title,
          author:user,
          snippet,
          description,
          // image,
          

        }),
        headers:{
            'Content-Type':'application/json',
            'Accept':'application/json',


        }

    }
    fetch('http://127.0.0.1:8000/api/v1/blogs/create/', options).
    then(res=>res.json()).then(response=> {
          console.log(response.author)
          setTitle('')
          setSnippet('')
          setDescription('')
          setImage(null)



    }).catch(error=>console.log(error))
  }

  // handleImageChange = (e) => {
  //   this.setState({image: e.target.files[0]})};
  const onFileChange = e => setImage(e.target.files[0])

  const handleLogout = async (e) =>{
    e.preventDefault();
    await logout()
  }

  // onFileCHange = e.target.files[0]

  return (
    <div className={styles.container}>
      <Head>
        <title></title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
        href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"
        rel="stylesheet"
      />
      <link
        href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
        rel="stylesheet"
      />
      <link
        href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/4.3.0/mdb.min.css"
        rel="stylesheet"
      />

<nav className="navbar navbar-expand-lg navbar-dark bg-dark">
  <div className="container">
    <a className="navbar-brand me-2" href="https://mdbgo.com/">
      <img
        src="https://mdbcdn.b-cdn.net/img/logo/mdb-transaprent-noshadows.webp"
        height="16"
        alt="MDB Logo"
        loading="lazy"
        // style="margin-top: -1px;"
      />
    </a>

    <button
      className="navbar-toggler"
      type="button"
      data-mdb-toggle="collapse"
      data-mdb-target="#navbarButtonsExample"
      aria-controls="navbarButtonsExample"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <i className="fas fa-bars"></i>
    </button>

    <div className="collapse navbar-collapse" id="navbarButtonsExample">
      <ul className="navbar-nav me-auto mb-2 mb-lg-0">
        <li className="nav-item">
          <a className="nav-link" href="#">Hi</a>

        </li>
      </ul>

      <div className="d-flex align-items-center">
      { user ? (

        <button type="button" className="btn btn-outline-secondary px-3 me-2"
         onClick={handleLogout}>
           Logout
        </button>
        ) : (
          <>
        <button type="button" className="btn btn-outline-secondary me-3"
        onClick={() => router.push('/accounts/register')}>
          Register
        </button>
        <button type="button" className="btn btn-outline-secondary me-3"
         onClick={() => router.push('/accounts/login')}>
          Login
        </button>
        </>
      )}

        
      </div>
    </div>
  </div>
</nav>
  </Head>
 {/* Posts*/} 
 <div className="container mt-4 mb-4">
   <div className="row mt-2 mb-2">
     <div className="col-md-1"></div>
     <div className="col-md-10">
       <div className="container mt-4 mb-4">
         <div className="row mt-2 mb-2">
         {blogs.map((blog) => (
              // <p>{blog.title}</p>
          <div className="col-md-3">
            <div className="card mt-2 mb-2 shadow-lg">
              <div className="card-body">
                <p className="card-text">{blog.title}</p>
                <div onClick={() => router.push(`/blogs/${blog.slug}`)}>
                <a className="card-text">{blog.slug}</a></div>

              </div>
            </div>
          </div>


            ))}


         </div>

       </div>
     </div>
     <div className="col-md-1"></div>

   </div>

 </div>
 



 {/* Posts*/} 
 <div className="container mt-4 mb-4">
   <div className="row mt-2 mb-2">
     <div className="col-md-3"></div>
     <div className="col-md-6">
      { user ? (
        <>
       <h6>Post Blog</h6>
     <form onSubmit={submitHandler}>
        
          <input  type="text" id="form4Example1" className="form-control mt-2 mb-2"  placeholder="Title"
          onChange={(e) => setTitle(e.target.value)}/>
          <input  type="text" id="form4Example2" className="form-control mt-2 mb-2" placeholder="Snippet"
          onChange={(e) => setSnippet(e.target.value)}/>
      
          <textarea className="form-control mt-2 mb-2" id="form4Example3" placeholder="Description" rows="4"
          onChange={(e) => setDescription(e.target.value)}></textarea>

         <input  type="file" class="form-control mt-2 mb-2" placeholder="upload image"
        onChange={onFileChange}/>


        <button type="submit" className="btn btn-primary btn-block mb-4 mt-2">Post</button>
        </form>
        </>
        ) : (
          <h6>Login to post</h6>
        )}

     </div>
     <div className="col-md-3"></div>

   </div>

 </div>


</div>
  )
}

export const getStaticProps=async()=>{
  const res=await axios.get("http://127.0.0.1:8000/api/v1/blogs/");
  return{
    props:{data:res.data},
 };
};